### ISSUE TITLE
Internal Server Error bei Null Values

### ISSUE THREAD

**Issue by Kamysek** [adorsys/XS2A-Sandbox#10]
Hallo, ich habe einen Internal Server Error bei Null Values erhalten. Anbei der Request, Response sowie der StackTrace.

**Request:**
Request method:	POST
Request URI:	http://localhost:8089/v1/consents
Proxy:			<none>
Request params:	<none>
Query params:	<none>
Form params:	<none>
Path params:	<none>
Headers:		X-Request-ID=2f77a125-aa7a-45c0-b414-c3a25a116136
				PSU-ID=kamysek
				psu-ip-address=1.1.1.1
				accept=application/json
				Content-Type=application/json; charset=UTF-8
Cookies:		<none>
Multiparts:		<none>
Body:
{
    "access": {
        "accounts": [
            {
                "iban": "DE17123456780000000001"
            }
        ]
    },
    "combinedServiceIndicator": "false",
    "validUntil": "2020-10-10",
    "recurringIndicator": "true",
    "frequencyPerDay": "15"
}

**Response:**
HTTP/1.1 500 
Content-Type: application/json;charset=UTF-8
Content-Length: 100
Date: Thu, 30 Jan 2020 16:04:52 GMT
Connection: close

{
    "tppMessages": [
        {
            "category": "ERROR",
            "code": "INTERNAL_SERVER_ERROR",
            "text": "Internal Server Error"
        }
    ]
}

**StackTrace:**
2020-01-29 18:23:41.996  WARN 1 --- [nio-8089-exec-4] a.p.x.e.GlobalExceptionHandlerController : Uncatched exception handled in Controller: ConsentApi, message: status 400 reading UserMgmtRestClient#multilevelAccounts(String,List), stackTrace: {} 
xs2a-connector-examples       | 
xs2a-connector-examples       | feign.FeignException: status 400 reading UserMgmtRestClient#multilevelAccounts(String,List)
xs2a-connector-examples       | 	at feign.FeignException.errorStatus(FeignException.java:78)
xs2a-connector-examples       | 	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:93)
xs2a-connector-examples       | 	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:149)
xs2a-connector-examples       | 	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:78)
xs2a-connector-examples       | 	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
xs2a-connector-examples       | 	at com.sun.proxy.$Proxy128.multilevelAccounts(Unknown Source)
xs2a-connector-examples       | 	at de.adorsys.aspsp.xs2a.connector.spi.impl.MultilevelScaServiceImpl.isMultilevelScaRequired(MultilevelScaServiceImpl.java:51)
xs2a-connector-examples       | 	at de.adorsys.aspsp.xs2a.connector.spi.impl.authorisation.AisConsentSpiImpl.isMultilevelScaRequired(AisConsentSpiImpl.java:287)
xs2a-connector-examples       | 	at de.adorsys.aspsp.xs2a.connector.spi.impl.authorisation.AisConsentSpiImpl.firstCallInstantiatingConsent(AisConsentSpiImpl.java:265)
xs2a-connector-examples       | 	at de.adorsys.aspsp.xs2a.connector.spi.impl.authorisation.AisConsentSpiImpl.initiateAisConsent(AisConsentSpiImpl.java:124)
xs2a-connector-examples       | 	at de.adorsys.psd2.xs2a.service.ConsentService.createAccountConsentsWithResponse(ConsentService.java:128)
xs2a-connector-examples       | 	at de.adorsys.psd2.xs2a.service.ConsentService$$FastClassBySpringCGLIB$$11a1f2af.invoke(<generated>)
xs2a-connector-examples       | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
xs2a-connector-examples       | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
xs2a-connector-examples       | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
xs2a-connector-examples       | 	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:55)
xs2a-connector-examples       | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
xs2a-connector-examples       | 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
xs2a-connector-examples       | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
xs2a-connector-examples       | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
xs2a-connector-examples       | 	at de.adorsys.psd2.xs2a.service.ConsentService$$EnhancerBySpringCGLIB$$8b1b48d1.createAccountConsentsWithResponse(<generated>)
xs2a-connector-examples       | 	at de.adorsys.psd2.xs2a.web.controller.ConsentController.createConsent(ConsentController.java:85)
xs2a-connector-examples       | 	at de.adorsys.psd2.api.ConsentApi._createConsent(ConsentApi.java:63)
xs2a-connector-examples       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
xs2a-connector-examples       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
xs2a-connector-examples       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
xs2a-connector-examples       | 	at java.lang.reflect.Method.invoke(Method.java:498)
xs2a-connector-examples       | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
xs2a-connector-examples       | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
xs2a-connector-examples       | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
xs2a-connector-examples       | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
xs2a-connector-examples       | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
xs2a-connector-examples       | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
xs2a-connector-examples       | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
xs2a-connector-examples       | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
xs2a-connector-examples       | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
xs2a-connector-examples       | 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
xs2a-connector-examples       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
xs2a-connector-examples       | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
xs2a-connector-examples       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
xs2a-connector-examples       | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
xs2a-connector-examples       | 	at de.adorsys.psd2.xs2a.web.filter.SignatureFilter.doFilterInternalCustom(SignatureFilter.java:70)
xs2a-connector-examples       | 	at de.adorsys.psd2.xs2a.web.filter.GlobalAbstractExceptionFilter.doFilterInternal(GlobalAbstractExceptionFilter.java:40)
xs2a-connector-examples       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
xs2a-connector-examples       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
xs2a-connector-examples       | 	at de.adorsys.psd2.xs2a.web.filter.ContentCachingWrappingFilter.doFilterInternalCustom(ContentCachingWrappingFilter.java:43)
xs2a-connector-examples       | 	at de.adorsys.psd2.xs2a.web.filter.GlobalAbstractExceptionFilter.doFilterInternal(GlobalAbstractExceptionFilter.java:40)
xs2a-connector-examples       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
xs2a-connector-examples       | 	at de.adorsys.psd2.xs2a.web.filter.QwacCertificateFilter.doFilterInternalCustom(QwacCertificateFilter.java:125)
xs2a-connector-examples       | 	at de.adorsys.psd2.xs2a.web.filter.GlobalAbstractExceptionFilter.doFilterInternal(GlobalAbstractExceptionFilter.java:40)
xs2a-connector-examples       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
xs2a-connector-examples       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
xs2a-connector-examples       | 	at de.adorsys.psd2.xs2a.web.filter.LoggingContextClearingFilter.doFilterInternalCustom(LoggingContextClearingFilter.java:45)
xs2a-connector-examples       | 	at de.adorsys.psd2.xs2a.web.filter.GlobalAbstractExceptionFilter.doFilterInternal(GlobalAbstractExceptionFilter.java:40)
xs2a-connector-examples       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
xs2a-connector-examples       | 	at de.adorsys.psd2.xs2a.web.filter.OauthModeFilter.doFilterInternalCustom(OauthModeFilter.java:99)
xs2a-connector-examples       | 	at de.adorsys.psd2.xs2a.web.filter.GlobalAbstractExceptionFilter.doFilterInternal(GlobalAbstractExceptionFilter.java:40)
xs2a-connector-examples       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
xs2a-connector-examples       | 	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
xs2a-connector-examples       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
xs2a-connector-examples       | 	at de.adorsys.aspsp.xs2a.connector.oauth.TokenAuthenticationFilter.doFilterInternalCustom(TokenAuthenticationFilter.java:86)
xs2a-connector-examples       | 	at de.adorsys.psd2.xs2a.web.filter.GlobalAbstractExceptionFilter.doFilterInternal(GlobalAbstractExceptionFilter.java:40)
xs2a-connector-examples       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
xs2a-connector-examples       | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
xs2a-connector-examples       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
xs2a-connector-examples       | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
xs2a-connector-examples       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
xs2a-connector-examples       | 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
xs2a-connector-examples       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
xs2a-connector-examples       | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
xs2a-connector-examples       | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
xs2a-connector-examples       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
xs2a-connector-examples       | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
xs2a-connector-examples       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
xs2a-connector-examples       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
xs2a-connector-examples       | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
xs2a-connector-examples       | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
xs2a-connector-examples       | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
xs2a-connector-examples       | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
xs2a-connector-examples       | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
xs2a-connector-examples       | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
xs2a-connector-examples       | 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:679)
xs2a-connector-examples       | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
xs2a-connector-examples       | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
xs2a-connector-examples       | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
xs2a-connector-examples       | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
xs2a-connector-examples       | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
xs2a-connector-examples       | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
xs2a-connector-examples       | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
xs2a-connector-examples       | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
xs2a-connector-examples       | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
xs2a-connector-examples       | 	at java.lang.Thread.run(Thread.java:748)

**Comment by jfractalus** [comment]
Hi Josef. Please give us more details about the version you used for running. Thanks

**Comment by DmitryMishchuk** [comment]
Please also provide the stacktrace from Ledgers.
