### ISSUE TITLE
No Data is Generated in adorsys TPP UI app

### ISSUE THREAD

**Issue by djole87** [adorsys/XS2A-Sandbox#11]
After successful user registration and login process, click on
> Generate Test Data

 does not generate any data.
Additionally, click on 
> My users list 

Throws the exception (attached). The screenshot is also attached.
[tpp_ui_exc.txt](https://github.com/adorsys/XS2A-Sandbox/files/4181279/tpp_ui_exc.txt)

![image](https://user-images.githubusercontent.com/8372413/74157962-83f53500-4c19-11ea-8459-ecd69697aafb.png)

**Comment by jfractalus** [comment]
Did you use the latest version? The latest version is:
Ledgers v.2.8
XS2A v.5.9
ASPSP-Profile v.5.9
Consent-Management v.5.9
XS2A Connector-Examples v.5.9

**Comment by djole87** [comment]
Problem was caused by outdated images
