### ISSUE TITLE
Online banking app - Redirect SCA approach problem

### ISSUE THREAD

**Issue by djole87** [adorsys/XS2A-Sandbox#12]
After following scaRedirect URL the following exception is thrown:

![image](https://user-images.githubusercontent.com/8372413/74161929-1ac4f000-4c20-11ea-892e-989e43b68e9a.png)

**Comment by jfractalus** [comment]
Hi. Seems you are using an outdated version.  The latest version is:
Ledgers v.2.8
XS2A v.5.9
ASPSP-Profile v.5.9
Consent-Management v.5.9
XS2A Connector-Examples v.5.9

**Comment by djole87** [comment]
The problem was caused by outdated images
