### ISSUE TITLE
ObaUI throws exception on Refresh transaction list 

### ISSUE THREAD

**Issue by djole87** [adorsys/XS2A-Sandbox#14]
Hi,

It seems that there is a problem with ObaUI app.
Exception from http://localhost:4400/oba-proxy/api/v1/ais/transactions/-kNvXeX-S7kt_Q7egoiJYA/page?size=10&page=0&dateTo=2020-02-28&dateFrom=2020-01-04

Components used:
1.Ledgers v.2.9
2.XS2A v.5.10
3.ASPSP-Profile v.5.10
4.Consent-Management v.5.10
5.XS2A Connector-Examples v.5.10

![image](https://user-images.githubusercontent.com/8372413/75558959-dff5f100-5a42-11ea-84e9-79d4c32ca740.png)

**Comment by jfractalus** [comment]
Hi, can you please attach the Log message?

**Comment by djole87** [comment]
Here it is:

`[ERROR][11:54:55.399] - de.adorsys.ledgers.oba.service.impl.service.AisServiceImpl: Failed to retrieve transactions for account: -kNvXeX-S7kt_Q7egoiJYA, code: 0, message: Error while extracting response for type [de.adorsys.ledgers.util.domain.CustomPageImpl<de.adorsys.ledgers.middleware.api.domain.account.TransactionTO>] and content type [application/json;charset=UTF-8]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Unrecognized field "balanceAfterTransaction" (class de.adorsys.ledgers.middleware.api.domain.account.TransactionTO), not marked as ignorable; nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "balanceAfterTransaction" (class de.adorsys.ledgers.middleware.api.domain.account.TransactionTO), not marked as ignorable (21 known properties: "endToEndId", "debtorName", "mandateId", "bookingDate", "purposeCode", "ultimateCreditor", "bankTransactionCode", "proprietaryBankTransactionCode", "creditorAccount", "creditorId", "amount", "transactionId", "valueDate", "checkId", "creditorName", "debtorAccount", "entryReference", "remittanceInformationStructured", "exchangeRate", "ultimateDebtor", "remittanceInformationUnstructured"])
xs2a-online-banking           |  at [Source: (ByteArrayInputStream); line: 1, column: 717] (through reference chain: de.adorsys.ledgers.util.domain.CustomPageImpl["content"]->java.util.ArrayList[0]->de.adorsys.ledgers.middleware.api.domain.account.TransactionTO["balanceAfterTransaction"])
`

**Comment by jfractalus** [comment]
XS2A-Connector-Examples 5.11 is compatible only with Ledgers 2.8, next release we will fix this problem

**Comment by jfractalus** [comment]
We will fix this problem in the next release

**Comment by jfractalus** [comment]
A new release is available. Please use https://github.com/adorsys/XS2A-Sandbox/blob/master/docker-compose-release.yml

**Comment by djole87** [comment]
Issue is fixed with the latest version! Will close it
