### ISSUE TITLE
List Account Transactions API call throws an error

### ISSUE THREAD

**Issue by djole87** [adorsys/XS2A-Sandbox#15]
Hi guys,

I'm using Sandbox 3.1.1 release and I'm facing error when trying to execute 

> GET /v1/accounts/{account-id}/transactions

Please find Exception with the stack trace attached.
[list_transaction_for_account_exc.txt](https://github.com/adorsys/XS2A-Sandbox/files/4307441/list_transaction_for_account_exc.txt)

**Comment by jfractalus** [comment]
Hi. Will be fixed after migration of Dynamic Sandbox on xs2a v5.11 and connector v5.11.1

**Comment by djole87** [comment]
Hi,
Thanks for the reply. 
Do you maybe know when this migration will be done?

**Comment by jfractalus** [comment]
I hope I will have enough time tomorrow to do that. I will let you know
immediately as soon as I finish
пн, 9 марта 2020 г. в 22:18, Djordje Stanojevic <notifications@github.com>:

**Comment by jfractalus** [comment]
I hope I will have enough time tomorrow to do that. I will let you know
immediately as soon as I finish

**Comment by jfractalus** [comment]
Hi. Please use the latest version of DS
https://github.com/adorsys/XS2A-Sandbox/releases/tag/3.2

**Comment by djole87** [comment]
with the latest version of DS it works
