### ISSUE TITLE
Unable to register a new TPP user on release 3.4 via TPP UI

### ISSUE THREAD

**Issue by f00bar** [adorsys/XS2A-Sandbox#20]
Hello,

I'm trying to start using the sandbox and register a TPP user via the UI but I can't get past this screen because of a call that's fetching the country code list to populate the form is returning 502 error

xs2a-tpp-ui_1                 | 172.20.0.1 - - [07/Apr/2020:15:03:12 +0000] "GET /tpp/codes HTTP/1.1" 502 157 "http://localhost:4205/register" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15"

<img width="1126" alt="Screenshot 2020-04-07 at 18 03 14" src="https://user-images.githubusercontent.com/14102/78685724-d3df3800-78fa-11ea-8443-91be74e1bfeb.png">

Any ideas on how to fix this?

Thanks!

**Comment by jfractalus** [comment]
Hi. We will take a look. Thanks

**Comment by jfractalus** [comment]
Just have checked v3.4 and couldn't reproduce the bug you mentioned. I propose to do the following:
To delete all containers including its volumes use,
1) docker rm -vf $(docker ps -a -q)
To delete all the images,
2) docker rmi -f $(docker images -a -q)
Remember, you should remove all the containers before removing all the images from which those containers were created.
3) docker volume rm $(docker volume ls -q)
After that execute 'make run' inside the root folder of the project

**Comment by f00bar** [comment]
@jfractalus I tried that a few times - no luck. I tried running it both with and without building it...

localhost:4205/tpp/codes returns 502 Bad Gategway from nginx which prevents the country codes from loading which prevents the registration page from working as expected for me.

**Comment by jfractalus** [comment]
Did you use the 'make run' command?

**Comment by f00bar** [comment]
yes I used make run

**Comment by jfractalus** [comment]
Please send me your docker compose log file to fractal567@gmail.com

**Comment by jfractalus** [comment]
Please try to increase allocated memory for docker up to 4.5
![image](https://user-images.githubusercontent.com/19815243/78721894-0c9a0400-7931-11ea-90cb-135f4102432f.png)

**Comment by f00bar** [comment]
@jfractalus Yeap - that solved the problem. After increasing the memory resources in Docker, I was able to launch the sandbox and the registration error no longer appears.

Thanks for the quick responses and congrats on the amazing software you've built! You may want to throw in a note for required Docker resources in the README so others don't experience the same issue. I believe I had the default Docker settings for Mac so others may bump into this as well.

**Comment by ViraHavrylenko** [comment]
Please take a look at https://github.com/adorsys/XS2A-Sandbox/blob/master/docs/running-xs2asandbox.md with Note already mentioned there.

**Comment by f00bar** [comment]
Great! You guys have created an amazing piece of software!

**Comment by jfractalus** [comment]
Thanks for such a feedback :)
