### ISSUE TITLE
Sandbox not returning User back to NOK URL

### ISSUE THREAD

**Issue by elroman** [adorsys/XS2A-Sandbox#21]
When we try to cancel the consent in page `/account-information/grant-consent` Sandbox redirects us to `ok-url `instead of `nok-url`

**Comment by ViraHavrylenko** [comment]
@elroman This bug is already known and will be fixed in XS2ASandbox v.3.5 (release planned for 21.04.2020)

**Comment by ViraHavrylenko** [comment]
@elroman fixed in XS2ASandbox v.3.5.1
