### ISSUE TITLE
Documentation (arc42) has some broken image links

### ISSUE THREAD

**Issue by leonardost78** [adorsys/XS2A-Sandbox#22]
When generating the documentation (arc42) the following links to images are wrong:

- ../images/deployment-view.svg
-../images/cpu_memory_load.png
-../images/oauth2_pre-authentication.png

References should be ./images insteadof ../images

**Comment by jfractalus** [comment]
Hi. Thanks. We will fix it in the nearest future.

**Comment by HryhoriiHevorkian** [comment]
This was fixed in version 3.5.1. Thanks for reporting!
