### ISSUE TITLE
challengeData object contains `data` field with array of null

### ISSUE THREAD

**Issue by berezkin88** [adorsys/XS2A-Sandbox#29]
If there is no `data` information in Challenge Data object, the corresponding field returns an array of _null_, e.g. 
![Screenshot 2020-06-09 at 16 48 19](https://user-images.githubusercontent.com/17544420/84155475-09c2a900-aa71-11ea-843f-b370032aa42b.png)

In such cases, additional checking for null is required for avoiding NPE.

It would be nice to have this field not present in the response if no _data_ is available.

**Comment by ViraHavrylenko** [comment]
@berezkin88 Fixed in XS2A-Sandbox v.4.2
