### ISSUE TITLE
Pending Transaction not visible in List of Transaction

### ISSUE THREAD

**Issue by elroman** [adorsys/XS2A-Sandbox#30]
After a new payment is done, LoT does not show this transaction. Client (e.g. fintech) is explicitly asking for bookingStatus "both".  The answer is just a list of booked transactions. No pending transactions are returned but expected to see pending transactions as well.
After PaymentExecutionScheduler has run, new payment is visible with status booked.

**Comment by ViraHavrylenko** [comment]
@elroman XS2A-Sandbox is working with emulation of core-banking-system called Ledgers, which supports bookingStatus=Booked only. Both and Pending are not supported yet.
