### ISSUE TITLE
A Vagrantfile would be 1A

### ISSUE THREAD

**Issue by chatelao** [adorsys/XS2A-Sandbox#4]
I'm struggeling to install the sandbox on CentOS

- Do you have a recommmended OS?
- Do you have automated provision scripts?

A "one-stopp" Vagrant file would be great.

**Comment by jfractalus** [comment]
Hi. Could you please describe the problem you faced during installing Sandbox on CentOS?

**Comment by openbankingproject-ch** [comment]
It is running now. It was due to:

a) The Vagrant directory "/Vagrant" mounted from Windows not allowing any sym-links
b) Beginners.troubles with all the dependencies.

Over all WHAT A GREAT PRODUCT, with a great future.

**Comment by jfractalus** [comment]
Thanks a lot for your warm feedback. Let us know if you have any questions
