### ISSUE TITLE
max.musterman wrong account balance for initial transactions

### ISSUE THREAD

**Issue by valb3r** [adorsys/XS2A-Sandbox#46]
When one launches vanilla Sandbox in DEV mode, user max.musterman is created.
He gets following transactions:
![Selection_142](https://user-images.githubusercontent.com/18463491/94934301-398c3580-04d4-11eb-9975-63a3fc654be5.png)

Calculated balance (` 10.120,00 ` visible on screenshot) does not seem to be correct, because:
Correct balance flow seem to be (operations done in order on screenshot)
1. debtor DE38760700240320465700 -> creditor DE69760700240340283600, amount -1280. Expected balance is (swap debtor, creditor as is negative, DE38760700240320465700 becomes creditor) -1280 on DE38760700240320465700
1. debtor DE38760700240320465700 -> creditor DE80760700240271232400, amount -2300. Expected balance is (swap debtor, creditor as is negative, DE38760700240320465700 becomes creditor) -1280-2300 on DE38760700240320465700
1. debtor DE80760700240271232400 -> creditor DE38760700240320465700, amount 700. Expected balance is -1280-2300-700 on DE38760700240320465700
1. debtor DE69760700240340283600 -> creditor DE38760700240320465700, amount 3000. Expected balance is -1280-2300-700-3000 on DE38760700240320465700
1. cash deposit (debtor/creditor DE38760700240320465700) Expected balance is -1280-2300-700-3000+10000 on DE38760700240320465700
This way displayed balance should be: `2720` instead of `10.120,00` 

Can someone clarify displayed balance logic?

**Comment by ViraHavrylenko** [comment]
Fixed in v.4.5
