### ISSUE TITLE
angular docker images in development mode by default

### ISSUE THREAD

**Issue by sofarsoghood** [adorsys/XS2A-Sandbox#91]
Hello everyone,

it seems that the docker images for the tpp-ui and also the online-banking-ui provided here:

- https://hub.docker.com/layers/adorsys/xs2a-bank-tpp-ui/5.14/images/sha256-9b766d520a9261f3e0a3baf58089733e22bac58d9bcb808df3272ac43114c1a8
- https://hub.docker.com/layers/adorsys/xs2a-online-banking-ui/5.14/images/sha256-e59720d7f1aaa0330ca0870c8952c128c829bc334851a7e8b16a8ca8fb6ccd63

are running in development mode by default (see attached screenshot). I couldn't find any straight forward solution to this (e.g. ENV var, etc.) beside changing the build commands and building the image on my own. Are you currently planning to also provide production-ready images, at least for the v5.14 on dockerhub?

Thank's a lot in advance!

![image](https://user-images.githubusercontent.com/3037077/146756708-8509b956-dfcc-434f-9e6c-6fb9a3dbe771.png)

**Comment by OlgaLevandovska** [comment]
Dear Alexandr,
we are currently using the development mode to run Docker images, but for the future releases we are able to switch to the production mode as well (there is no difference in functionality between these modes, so you can use the existing one). 

According to the release policy new changes will be delivered to Github community in the middle of this year.
